# Generated by Django 4.2.4 on 2023-09-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlemodel_item_id'),
        ('admin_panel', '0002_item_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
