# Generated by Django 4.2.4 on 2023-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
