# Generated by Django 4.2.4 on 2023-10-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cartitem_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razorpay_signature',
        ),
    ]
