# Generated by Django 4.2.4 on 2023-09-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
